### ISSUE TITLE
Cannot access the app from a remote host.

### ISSUE THREAD

**Issue by piotrgrubicki** [open-edge-platform/anomalib#3488]
1. Start the app by `AI_DEVICE=xpu docker compose up` (I provided HOST in docker-compuse.yaml to overcome the problem from #3485 ).
2. Open `http:<IP>:8000` in your browser on another machine (all the ports are available, both UI, and api can be accessed).
3. Ensure the Anomalib Suite welcome page is opened.
4. Click Create project.

Nothing happens. The JS console reveals:
```
Uncaught TypeError: crypto.randomUUID is not a function
```
If I set up port forwarding and use `http://localhost:8000` to open the app, it works properly.

This change has been introduced in #3470 
crypto.randomUUID can be used only in secure context (https and http on localhost), which is not the case in my scenario.

**Comment by HenkieTenkie62** [comment]
I fixed it by running it on a local machine and opening localhost:<port> or remote by putting it behind https proxy with nginx to access it from another machine
